<h1>{{ $concert->title }}</h1>
<h2>{{ $concert->subtitle }}</h2>
<small>{{ $concert->formatted_date }}</small>
<p>{{ $concert->ticket_price }}</p>
<p>{{ $concert->venue }}</p>
<p>{{ $concert->venue_address }}</p>
<p>{{ $concert->city }}</p>
<p>{{ $concert->state }}</p>
<p>{{ $concert->zip }}</p>
<p>{{ $concert->additional_information }}</p>
