version: '3'

services:
  blog-server:
    build: ./provisioning
    image: server
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/var/www/laravel:cached

  horizon:
    build: ./provisioning
    image: horizon
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/laravel:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  mysql-test:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www/laravel:cached
    depends_on:
      - blog-server

  redis:
    image: redis
    ports:
      - "6378:6379"

  echo-server:
    image: node
    ports:
      - "8888:8888"
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel:cached
    depends_on:
      - redis
      - blog-server
    command: 'npm start'

  node:
    image: node:10.10.0-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
